apiVersion: apps/v1
kind: Deployment
metadata:
  name: custommerCenter
  labels:
    app: custommerCenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custommerCenter
  template:
    metadata:
      labels:
        app: custommerCenter
    spec:
      containers:
        - name: custommerCenter
          image: dongeunkim/customerenter:v230214
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
